server:
  port: 8081
spring:
  application:
    name: vue-springBoot-curd-team4-lizhihao
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/vue_springBoot_curd?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: lzh1998620
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
