server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: admin

  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: src/main